#!/bin/sh
#----------------------------------------------------------------------
# efunge - a Befunge-98 interpreter in Erlang.
# Copyright (C) 2008-2010 Arvid Norlander <anmaster AT tele2 DOT se>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#----------------------------------------------------------------------
# Path of efunge, set to where you install the compiled beam files.
EFUNGE_ROOT=./ebin
# Filename of efunge to check for
EFUNGENAME=efunge.beam

# Sanity checks
if [ $# -lt 1 ]; then
	echo "Too few arguments!"
	echo
	echo "Usage: $0 filename [ARGS]"
	exit 1
fi
if [ ! -e "$1" ] || [ ! -r "$1" ]; then
	echo "Can not process the given file, check that it exists and that its"
	echo "permissions are correct."
	exit 1
fi
if [ ! -d "$EFUNGE_ROOT" ]; then
	echo "efunge directory not found"
	exit 1
fi
if [ ! -e "$EFUNGE_ROOT/$EFUNGENAME" ]; then
	echo "efunge.beam not found. Did you forget make?"
	exit 1
fi
if ! type erl > /dev/null 2>&1; then
	echo "erl not found in your PATH, can't run efunge without it!"
	exit 1
fi
# Run it then...
exec erl -noshell -pa "$EFUNGE_ROOT" -run efunge run -extra ${1+"$@"}
